name: Build and Push

on:
  create:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: install podman
      run: sudo apt-get -y install podman buildah

    - uses: redhat-actions/podman-login@v1
      with:
        username: ${{ secrets.QUAY_ROBOT_NAME }}
        password: ${{ secrets.QUAY_ROBOT_PASSWORD }}
        registry: quay.io

    - run: sudo podman run --net=host --rm --privileged ghcr.io/nalind/fedora-qemu-user-static register

#    - uses: redhat-actions/buildah-build@v2
#      with:
#        containerfiles: Dockerfile
#        context: .
#        image: localhost/nonce
#        extra-args: --all-platforms --manifest localhost/doge-image

    - run: buildah version

    - run: buildah build --net=host --manifest localhost/doge-image --platform linux/arm64,linux/amd64,linux/ppc64le,linux/s390x .

    - run: if test "${GITHUB_EVENT_NAME}" = create -a "${GITHUB_REF_TYPE}" = tag ; then podman manifest push --all --format v2s2 localhost/doge-image quay.io/nalind/doge-image:"${GITHUB_REF_NAME}" ; else podman manifest push --all --format v2s2 localhost/doge-image quay.io/nalind/doge-image:latest; fi
